//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoversDBEntities : DbContext
    {
        public MoversDBEntities()
            : base("name=MoversDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<allMySons2> allMySons2 { get; set; }
        public DbSet<dtproperty> dtproperties { get; set; }
        public DbSet<IsAliasMail_Log> IsAliasMail_Log { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<recRevenue> recRevenues { get; set; }
        public DbSet<STATES_NAME> STATES_NAME { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tbl_123bannerPricing> tbl_123bannerPricing { get; set; }
        public DbSet<tbl_123bannerPricing_new> tbl_123bannerPricing_new { get; set; }
        public DbSet<tbl_123moversBannerPricingModel> tbl_123moversBannerPricingModel { get; set; }
        public DbSet<tbl_123moversPricing> tbl_123moversPricing { get; set; }
        public DbSet<tbl_123moversPricing_new> tbl_123moversPricing_new { get; set; }
        public DbSet<tbl_123moversPricingModel> tbl_123moversPricingModel { get; set; }
        public DbSet<tbl_adminEmployees> tbl_adminEmployees { get; set; }
        public DbSet<tbl_adServiceState> tbl_adServiceState { get; set; }
        public DbSet<tbl_Advertise> tbl_Advertise { get; set; }
        public DbSet<tbl_affilaiteLoginTrack> tbl_affilaiteLoginTrack { get; set; }
        public DbSet<tbl_affiliate> tbl_affiliate { get; set; }
        public DbSet<tbl_affiliate_coBrand> tbl_affiliate_coBrand { get; set; }
        public DbSet<tbl_affiliate_CobrandNew> tbl_affiliate_CobrandNew { get; set; }
        public DbSet<tbl_affiliateAutoPricingByAreaCode> tbl_affiliateAutoPricingByAreaCode { get; set; }
        public DbSet<tbl_affiliateAutoQuotePricingByAreaCode> tbl_affiliateAutoQuotePricingByAreaCode { get; set; }
        public DbSet<tbl_affiliateMain> tbl_affiliateMain { get; set; }
        public DbSet<tbl_affiliateNotifyAfterLeadSold> tbl_affiliateNotifyAfterLeadSold { get; set; }
        public DbSet<tbl_affiliatePricingByAreaCode> tbl_affiliatePricingByAreaCode { get; set; }
        public DbSet<tbl_affiliateQuotePricingByAreaCode> tbl_affiliateQuotePricingByAreaCode { get; set; }
        public DbSet<tbl_affiliateReport> tbl_affiliateReport { get; set; }
        public DbSet<tbl_affiliateReportClicks> tbl_affiliateReportClicks { get; set; }
        public DbSet<tbl_affiliateReportSE> tbl_affiliateReportSE { get; set; }
        public DbSet<tbl_agentsAdvertise> tbl_agentsAdvertise { get; set; }
        public DbSet<tbl_AllListMoving> tbl_AllListMoving { get; set; }
        public DbSet<tbl_AllListStorage> tbl_AllListStorage { get; set; }
        public DbSet<tbl_areaCodeAnalysis> tbl_areaCodeAnalysis { get; set; }
        public DbSet<tbl_areaCodeLeadsCount> tbl_areaCodeLeadsCount { get; set; }
        public DbSet<tbl_areacodeserviceWithNoMovers> tbl_areacodeserviceWithNoMovers { get; set; }
        public DbSet<tbl_articlesForHomePage> tbl_articlesForHomePage { get; set; }
        public DbSet<tbl_Auto> tbl_Auto { get; set; }
        public DbSet<tbl_auto_opt_companyMain> tbl_auto_opt_companyMain { get; set; }
        public DbSet<tbl_availabilityListArchives> tbl_availabilityListArchives { get; set; }
        public DbSet<tbl_availabilityListExclusiveLeadCount> tbl_availabilityListExclusiveLeadCount { get; set; }
        public DbSet<tbl_badName> tbl_badName { get; set; }
        public DbSet<tbl_badPhoneNumbers> tbl_badPhoneNumbers { get; set; }
        public DbSet<tbl_ballot> tbl_ballot { get; set; }
        public DbSet<tbl_bhTrack> tbl_bhTrack { get; set; }
        public DbSet<tbl_bkUpgradeDowngradeCancellation> tbl_bkUpgradeDowngradeCancellation { get; set; }
        public DbSet<tbl_blackListIPnEmail> tbl_blackListIPnEmail { get; set; }
        public DbSet<tbl_blockedSe> tbl_blockedSe { get; set; }
        public DbSet<tbl_broadband> tbl_broadband { get; set; }
        public DbSet<tbl_callsource> tbl_callsource { get; set; }
        public DbSet<tbl_campaignInfo> tbl_campaignInfo { get; set; }
        public DbSet<tbl_campaignVerification> tbl_campaignVerification { get; set; }
        public DbSet<tbl_cityArticle> tbl_cityArticle { get; set; }
        public DbSet<tbl_collectionList> tbl_collectionList { get; set; }
        public DbSet<tbl_company> tbl_company { get; set; }
        public DbSet<tbl_company_flagLeads> tbl_company_flagLeads { get; set; }
        public DbSet<tbl_company_metatags> tbl_company_metatags { get; set; }
        public DbSet<tbl_company_storage> tbl_company_storage { get; set; }
        public DbSet<tbl_companyAdByArea> tbl_companyAdByArea { get; set; }
        public DbSet<tbl_companyAreacode> tbl_companyAreacode { get; set; }
        public DbSet<tbl_companyAreacode_auto_opt> tbl_companyAreacode_auto_opt { get; set; }
        public DbSet<tbl_companyAssociation> tbl_companyAssociation { get; set; }
        public DbSet<tbl_companyBudget> tbl_companyBudget { get; set; }
        public DbSet<tbl_companyBudget_PayingLater> tbl_companyBudget_PayingLater { get; set; }
        public DbSet<tbl_companyBudgetAutoRenewBySPOnlyForReference> tbl_companyBudgetAutoRenewBySPOnlyForReference { get; set; }
        public DbSet<tbl_companyBudgetRenew> tbl_companyBudgetRenew { get; set; }
        public DbSet<tbl_companyCancellations> tbl_companyCancellations { get; set; }
        public DbSet<tbl_companyCancellationsLog> tbl_companyCancellationsLog { get; set; }
        public DbSet<tbl_companyCountries> tbl_companyCountries { get; set; }
        public DbSet<tbl_companyCreditBudget> tbl_companyCreditBudget { get; set; }
        public DbSet<tbl_companyDestinationAreaCodesZipCodes> tbl_companyDestinationAreaCodesZipCodes { get; set; }
        public DbSet<tbl_companyDifferentTextFormat> tbl_companyDifferentTextFormat { get; set; }
        public DbSet<tbl_companyLeadLimit> tbl_companyLeadLimit { get; set; }
        public DbSet<tbl_companyLoginTrack> tbl_companyLoginTrack { get; set; }
        public DbSet<tbl_companyMain> tbl_companyMain { get; set; }
        public DbSet<tbl_companyManualEmailsLog> tbl_companyManualEmailsLog { get; set; }
        public DbSet<tbl_companyMinDistance> tbl_companyMinDistance { get; set; }
        public DbSet<tbl_companyMoveDate> tbl_companyMoveDate { get; set; }
        public DbSet<tbl_companyMoveDistance> tbl_companyMoveDistance { get; set; }
        public DbSet<tbl_companyMoveWeight> tbl_companyMoveWeight { get; set; }
        public DbSet<tbl_companyMultiAreas> tbl_companyMultiAreas { get; set; }
        public DbSet<tbl_companyOriginZipCodes> tbl_companyOriginZipCodes { get; set; }
        public DbSet<tbl_companyPhoneAreaMapping> tbl_companyPhoneAreaMapping { get; set; }
        public DbSet<tbl_companyPricePerLead> tbl_companyPricePerLead { get; set; }
        public DbSet<tbl_companyQuoteTrack> tbl_companyQuoteTrack { get; set; }
        public DbSet<tbl_companyRefundLeads> tbl_companyRefundLeads { get; set; }
        public DbSet<tbl_companyRefundLeadsReasons> tbl_companyRefundLeadsReasons { get; set; }
        public DbSet<tbl_companyRefundReasons> tbl_companyRefundReasons { get; set; }
        public DbSet<tbl_companySpecificOriginDestinationAreacode> tbl_companySpecificOriginDestinationAreacode { get; set; }
        public DbSet<tbl_companySpecificOriginDestinationState> tbl_companySpecificOriginDestinationState { get; set; }
        public DbSet<tbl_companyVlAgents> tbl_companyVlAgents { get; set; }
        public DbSet<tbl_complaints> tbl_complaints { get; set; }
        public DbSet<tbl_confirmInfo> tbl_confirmInfo { get; set; }
        public DbSet<tbl_consentSeValue> tbl_consentSeValue { get; set; }
        public DbSet<tbl_content> tbl_content { get; set; }
        public DbSet<tbl_countries> tbl_countries { get; set; }
        public DbSet<tbl_countriesDesc> tbl_countriesDesc { get; set; }
        public DbSet<tbl_CPC> tbl_CPC { get; set; }
        public DbSet<tbl_cpcContent> tbl_cpcContent { get; set; }
        public DbSet<tbl_cpcContentHandle> tbl_cpcContentHandle { get; set; }
        public DbSet<tbl_CPM> tbl_CPM { get; set; }
        public DbSet<tbl_customerMain> tbl_customerMain { get; set; }
        public DbSet<tbl_dailyAffilaiteBudget> tbl_dailyAffilaiteBudget { get; set; }
        public DbSet<tbl_dailyBudgetAffiliateData> tbl_dailyBudgetAffiliateData { get; set; }
        public DbSet<tbl_dailyBudgetConfig> tbl_dailyBudgetConfig { get; set; }
        public DbSet<tbl_dailyBudgetReport> tbl_dailyBudgetReport { get; set; }
        public DbSet<tbl_desiredAreaCodePrices> tbl_desiredAreaCodePrices { get; set; }
        public DbSet<tbl_disableFreeCompanies> tbl_disableFreeCompanies { get; set; }
        public DbSet<tbl_emailDetailsFromRealTimeAPI> tbl_emailDetailsFromRealTimeAPI { get; set; }
        public DbSet<tbl_emailFilterAPI> tbl_emailFilterAPI { get; set; }
        public DbSet<tbl_EmailFormatAffiliate> tbl_EmailFormatAffiliate { get; set; }
        public DbSet<tbl_emailValidationDetails> tbl_emailValidationDetails { get; set; }
        public DbSet<tbl_exclusiveCompany> tbl_exclusiveCompany { get; set; }
        public DbSet<tbl_exclusiveCompany_log> tbl_exclusiveCompany_log { get; set; }
        public DbSet<tbl_exclusiveCompanyZipAreaException> tbl_exclusiveCompanyZipAreaException { get; set; }
        public DbSet<tbl_exclusiveLeadCounter> tbl_exclusiveLeadCounter { get; set; }
        public DbSet<tbl_exclusivePricing> tbl_exclusivePricing { get; set; }
        public DbSet<tbl_exclusiveService> tbl_exclusiveService { get; set; }
        public DbSet<tbl_exclusiveService_log> tbl_exclusiveService_log { get; set; }
        public DbSet<tbl_exclusiveSirvaCompanyLookUp> tbl_exclusiveSirvaCompanyLookUp { get; set; }
        public DbSet<tbl_FacebookLandingPage> tbl_FacebookLandingPage { get; set; }
        public DbSet<tbl_farmerBannerResponse> tbl_farmerBannerResponse { get; set; }
        public DbSet<tbl_fileNamePerm> tbl_fileNamePerm { get; set; }
        public DbSet<tbl_filterByDestination> tbl_filterByDestination { get; set; }
        public DbSet<tbl_homePagePhone> tbl_homePagePhone { get; set; }
        public DbSet<tbl_identifiers> tbl_identifiers { get; set; }
        public DbSet<tbl_Intl> tbl_Intl { get; set; }
        public DbSet<tbl_invalidQuotes> tbl_invalidQuotes { get; set; }
        public DbSet<tbl_inValidQuotes_displayReasons> tbl_inValidQuotes_displayReasons { get; set; }
        public DbSet<tbl_inValidQuotes_reasons> tbl_inValidQuotes_reasons { get; set; }
        public DbSet<tbl_keywordIdentity> tbl_keywordIdentity { get; set; }
        public DbSet<tbl_landingpagecontent> tbl_landingpagecontent { get; set; }
        public DbSet<tbl_leadPostResponse> tbl_leadPostResponse { get; set; }
        public DbSet<tbl_LeadsReport> tbl_LeadsReport { get; set; }
        public DbSet<tbl_listLinks> tbl_listLinks { get; set; }
        public DbSet<tbl_listMain> tbl_listMain { get; set; }
        public DbSet<tbl_lookUpAffiliatePricing> tbl_lookUpAffiliatePricing { get; set; }
        public DbSet<tbl_lowRevenueAreaCodes> tbl_lowRevenueAreaCodes { get; set; }
        public DbSet<tbl_manageUpgradeDowngradeAds> tbl_manageUpgradeDowngradeAds { get; set; }
        public DbSet<tbl_manageUpgradeDowngradeArea> tbl_manageUpgradeDowngradeArea { get; set; }
        public DbSet<tbl_monthly> tbl_monthly { get; set; }
        public DbSet<tbl_monthlyAreaCodeLeadCount> tbl_monthlyAreaCodeLeadCount { get; set; }
        public DbSet<tbl_mortgageLeadInfo> tbl_mortgageLeadInfo { get; set; }
        public DbSet<tbl_Movers> tbl_Movers { get; set; }
        public DbSet<tbl_MoveSizelookup> tbl_MoveSizelookup { get; set; }
        public DbSet<tbl_MoveSizelookup_V2> tbl_MoveSizelookup_V2 { get; set; }
        public DbSet<tbl_movingsurvey> tbl_movingsurvey { get; set; }
        public DbSet<tbl_newsletter> tbl_newsletter { get; set; }
        public DbSet<tbl_newsletterUnsub> tbl_newsletterUnsub { get; set; }
        public DbSet<tbl_NewStateDesc> tbl_NewStateDesc { get; set; }
        public DbSet<tbl_notAllowForSpecialBenefits> tbl_notAllowForSpecialBenefits { get; set; }
        public DbSet<tbl_numCompPerArea> tbl_numCompPerArea { get; set; }
        public DbSet<tbl_p4pOffers> tbl_p4pOffers { get; set; }
        public DbSet<tbl_p4pOffersPostLog> tbl_p4pOffersPostLog { get; set; }
        public DbSet<tbl_p4pPostLog> tbl_p4pPostLog { get; set; }
        public DbSet<tbl_pageContent> tbl_pageContent { get; set; }
        public DbSet<tbl_pageMain> tbl_pageMain { get; set; }
        public DbSet<tbl_paidComp> tbl_paidComp { get; set; }
        public DbSet<tbl_paidComp_inactive> tbl_paidComp_inactive { get; set; }
        public DbSet<tbl_phone> tbl_phone { get; set; }
        public DbSet<tbl_phoneOLD> tbl_phoneOLD { get; set; }
        public DbSet<tbl_poll> tbl_poll { get; set; }
        public DbSet<tbl_processDetails> tbl_processDetails { get; set; }
        public DbSet<tbl_quoteAnalysis> tbl_quoteAnalysis { get; set; }
        public DbSet<tbl_quoteAuto> tbl_quoteAuto { get; set; }
        public DbSet<tbl_quoteDestinationzip> tbl_quoteDestinationzip { get; set; }
        public DbSet<tbl_quoteMoving> tbl_quoteMoving { get; set; }
        public DbSet<tbl_quoteRequests> tbl_quoteRequests { get; set; }
        public DbSet<tbl_quoteSelfMoving> tbl_quoteSelfMoving { get; set; }
        public DbSet<tbl_quoteStorage> tbl_quoteStorage { get; set; }
        public DbSet<tbl_realEstateAgents> tbl_realEstateAgents { get; set; }
        public DbSet<tbl_realtimeReversePhoneLookup> tbl_realtimeReversePhoneLookup { get; set; }
        public DbSet<tbl_recordPostInformation> tbl_recordPostInformation { get; set; }
        public DbSet<tbl_RecPostData> tbl_RecPostData { get; set; }
        public DbSet<tbl_RestrictServiceAreaPerSE> tbl_RestrictServiceAreaPerSE { get; set; }
        public DbSet<tbl_resultPageContent> tbl_resultPageContent { get; set; }
        public DbSet<tbl_reverseVerificationCheck> tbl_reverseVerificationCheck { get; set; }
        public DbSet<tbl_reverseVerificationLeads> tbl_reverseVerificationLeads { get; set; }
        public DbSet<tbl_reverseVerificationLeadsCall> tbl_reverseVerificationLeadsCall { get; set; }
        public DbSet<tbl_reverseVerificationLeadsCallLog> tbl_reverseVerificationLeadsCallLog { get; set; }
        public DbSet<tbl_reverseVerificationLeadsEmail> tbl_reverseVerificationLeadsEmail { get; set; }
        public DbSet<tbl_reverseVerificationLeadsEmailLog> tbl_reverseVerificationLeadsEmailLog { get; set; }
        public DbSet<tbl_reverseVerificationMaskPhone> tbl_reverseVerificationMaskPhone { get; set; }
        public DbSet<tbl_reverseVerifiedLeadsLog> tbl_reverseVerifiedLeadsLog { get; set; }
        public DbSet<tbl_reviews> tbl_reviews { get; set; }
        public DbSet<tbl_reviewsReply> tbl_reviewsReply { get; set; }
        public DbSet<tbl_Satellite> tbl_Satellite { get; set; }
        public DbSet<tbl_service> tbl_service { get; set; }
        public DbSet<tbl_serviceLeadsCount> tbl_serviceLeadsCount { get; set; }
        public DbSet<tbl_serviceMain> tbl_serviceMain { get; set; }
        public DbSet<tbl_seTotalLeads> tbl_seTotalLeads { get; set; }
        public DbSet<tbl_sirvaZipCodes> tbl_sirvaZipCodes { get; set; }
        public DbSet<tbl_stateDesc> tbl_stateDesc { get; set; }
        public DbSet<tbl_Storage> tbl_Storage { get; set; }
        public DbSet<tbl_TexasProject> tbl_TexasProject { get; set; }
        public DbSet<tbl_tips> tbl_tips { get; set; }
        public DbSet<tbl_trackAdsMaster> tbl_trackAdsMaster { get; set; }
        public DbSet<tbl_trackCompPage> tbl_trackCompPage { get; set; }
        public DbSet<tbl_trackCompPageEven> tbl_trackCompPageEven { get; set; }
        public DbSet<tbl_trackCompPageOdd> tbl_trackCompPageOdd { get; set; }
        public DbSet<tbl_trackOffers> tbl_trackOffers { get; set; }
        public DbSet<tbl_trackSePosts> tbl_trackSePosts { get; set; }
        public DbSet<tbl_upgradeDowngradesCancelStatusLog> tbl_upgradeDowngradesCancelStatusLog { get; set; }
        public DbSet<tbl_URLshortenAPI> tbl_URLshortenAPI { get; set; }
        public DbSet<tbl_userConsentSold> tbl_userConsentSold { get; set; }
        public DbSet<tbl_vote> tbl_vote { get; set; }
        public DbSet<tbl_zip> tbl_zip { get; set; }
        public DbSet<tbl_zipNew_Front> tbl_zipNew_Front { get; set; }
        public DbSet<tbl_zipNewAreasSwitchToOld> tbl_zipNewAreasSwitchToOld { get; set; }
        public DbSet<tbl_zipOld> tbl_zipOld { get; set; }
        public DbSet<tbl_zipv2> tbl_zipv2 { get; set; }
        public DbSet<tempCompany> tempCompanies { get; set; }
        public DbSet<tl_company_activities_log> tl_company_activities_log { get; set; }
        public DbSet<tl_company_advertisement_log> tl_company_advertisement_log { get; set; }
        public DbSet<tl_company_areacodes_log> tl_company_areacodes_log { get; set; }
        public DbSet<tl_company_countries_log> tl_company_countries_log { get; set; }
        public DbSet<tl_company_deletelistings_log> tl_company_deletelistings_log { get; set; }
        public DbSet<tl_company_storage_log> tl_company_storage_log { get; set; }
        public DbSet<tl_companyBudget> tl_companyBudget { get; set; }
        public DbSet<tl_companyBudgetRenew> tl_companyBudgetRenew { get; set; }
        public DbSet<tl_companyPricePerLead> tl_companyPricePerLead { get; set; }
        public DbSet<tl_numCompPerArea_log> tl_numCompPerArea_log { get; set; }
        public DbSet<tl_postInformation> tl_postInformation { get; set; }
        public DbSet<tl_quoteRequests> tl_quoteRequests { get; set; }
        public DbSet<tlk_companiesWith25pctDiscount> tlk_companiesWith25pctDiscount { get; set; }
        public DbSet<tlk_companiesWith25pctDiscount070108> tlk_companiesWith25pctDiscount070108 { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
