//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoversDBEntities : DbContext
    {
        public MoversDBEntities()
            : base("name=MoversDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Log> Logs { get; set; }
        public DbSet<tbl_company> tbl_company { get; set; }
        public DbSet<tbl_companyAreacode> CompanyAreacode { get; set; }
        public DbSet<tbl_companyBudget> CompanyBudget { get; set; }
        public DbSet<tbl_companyBudgetRenew> CompanyBudgetRenew { get; set; }
        public DbSet<tbl_companyDestinationAreaCodesZipCodes> CompanyDestinationAreaCodesZipCodes { get; set; }
        public DbSet<tbl_companyLeadLimit> CompanyLeadLimit { get; set; }
        public DbSet<tbl_companyMain> CompanyMain { get; set; }
        public DbSet<tbl_companyMoveDistance> CompanyMoveDistance { get; set; }
        public DbSet<tbl_companyMoveWeight> CompanyMoveWeight { get; set; }
        public DbSet<tbl_companyOriginZipCodes> CompanyOriginZipCodes { get; set; }
        public DbSet<tbl_companyPhoneAreaMapping> CompanyPhoneAreaMapping { get; set; }
        public DbSet<tbl_companyPricePerLead> CompanyPricePerLead { get; set; }
        public DbSet<tbl_companySpecificOriginDestinationAreacode> CompanySpecificOriginDestinationAreacode { get; set; }
        public DbSet<tbl_companySpecificOriginDestinationState> CompanySpecificOriginDestinationState { get; set; }
        public DbSet<tbl_MoveSizelookup_V2> MoveSizelookup_V2 { get; set; }
        public DbSet<tbl_zip> Zip { get; set; }
        public DbSet<tl_companyBudget> tl_companyBudget { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
