//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class recRevenue
    {
        public int tid { get; set; }
        public string companyName { get; set; }
        public string AB { get; set; }
        public string C_date { get; set; }
        public string SiteId { get; set; }
        public string ObjAcct { get; set; }
        public string Remark { get; set; }
        public string Product { get; set; }
        public string Rep { get; set; }
        public string Total { get; set; }
        public Nullable<decimal> C_total1 { get; set; }
        public Nullable<int> companyID { get; set; }
        public string formatDate { get; set; }
        public System.DateTime insertDate { get; set; }
    }
}
