//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATES_NAME
    {
        public short STATE_ID { get; set; }
        public string STATE_SHORTNAME { get; set; }
        public string STATE_FULLNAME { get; set; }
    }
}
