//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_confirmInfo
    {
        public int tid { get; set; }
        public int quoteID { get; set; }
        public string cityFrom { get; set; }
        public string stateFrom { get; set; }
        public string cityTo { get; set; }
        public string stateTo { get; set; }
        public string moveWeight { get; set; }
        public string categoryName { get; set; }
        public string moveDate { get; set; }
        public bool isDup { get; set; }
        public string remoteHost { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
