//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_companyCancellationsLog
    {
        public int tid { get; set; }
        public int companyID { get; set; }
        public string who { get; set; }
        public string reasonMain { get; set; }
        public string reason { get; set; }
        public decimal cpl { get; set; }
        public decimal lostRevenue { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
