//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emailFilterAPI
    {
        public int tid { get; set; }
        public bool ApplyEmailFilter { get; set; }
        public int totalAllowedCalls { get; set; }
        public int monthlyCallsCounter { get; set; }
        public System.DateTime dateModified { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
