//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_exclusiveService_log
    {
        public int tid { get; set; }
        public string areaCode { get; set; }
        public int serviceID { get; set; }
        public bool isExclusiveService { get; set; }
        public bool isDailyLeadsLimit { get; set; }
        public int dailyLeadsLimit { get; set; }
        public int monthlyLeadLimit { get; set; }
        public int frequency { get; set; }
        public decimal maxCPLForCompany { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
