//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mortgageLeadInfo
    {
        public int mID { get; set; }
        public Nullable<int> loanpurpose { get; set; }
        public string propstate { get; set; }
        public Nullable<int> loanamount { get; set; }
        public Nullable<int> brrwrcreditrating { get; set; }
        public string brrwrfname { get; set; }
        public Nullable<int> loanproduct { get; set; }
        public string loanclosedate { get; set; }
        public string brrwremail { get; set; }
        public Nullable<int> propvalue { get; set; }
        public Nullable<int> brrwrbankruptcy { get; set; }
        public string brrwrlname { get; set; }
        public Nullable<int> brrwrdocumentincome { get; set; }
        public string brrwrhomephone1 { get; set; }
        public string brrwrhomephone2 { get; set; }
        public string brrwrhomephone3 { get; set; }
        public string brrwrworkphone1 { get; set; }
        public string brrwrworkphone2 { get; set; }
        public string brrwrworkphone3 { get; set; }
        public System.DateTime dateLead { get; set; }
        public string propcity { get; set; }
        public string propzip { get; set; }
        public string propaddress { get; set; }
    }
}
