//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_areaCodeAnalysis
    {
        public int tid { get; set; }
        public int areaCode { get; set; }
        public string longState { get; set; }
        public int serviceID { get; set; }
        public int compCount { get; set; }
        public int numOfLeadsLast30Days { get; set; }
        public decimal monthlyFeeOfThisAreaCode { get; set; }
        public int AvgLeadsTheCompanyReceive { get; set; }
        public decimal AvgPriceOfLeadPerCompany { get; set; }
        public string source { get; set; }
        public string type { get; set; }
        public int totalLeads { get; set; }
        public decimal cost { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
