//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_companyAssociation
    {
        public int tid { get; set; }
        public string companyHandle { get; set; }
        public string AssociatedCompanyHandle { get; set; }
        public string ReasonOfAssociation { get; set; }
        public System.DateTime dateSubmitted { get; set; }
    }
}
