//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_leadPostResponse
    {
        public int tid { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<int> quoteID { get; set; }
        public string postRequest { get; set; }
        public string postResponse { get; set; }
        public Nullable<System.DateTime> stampDate { get; set; }
    }
}
