//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_newsletter
    {
        public int Nid { get; set; }
        public string Newsletter_Name { get; set; }
        public System.DateTime datecreated { get; set; }
        public string from { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public byte isCustom { get; set; }
        public Nullable<int> moving { get; set; }
        public Nullable<int> auto { get; set; }
        public Nullable<int> storage { get; set; }
        public int delay { get; set; }
        public Nullable<byte> isActive { get; set; }
    }
}
