//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_keywordIdentity
    {
        public string Campaign { get; set; }
        public string OldKeyword { get; set; }
        public string ActiveCodeKeyword { get; set; }
        public string MatchingCodeKeyword { get; set; }
    }
}
