//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CPC
    {
        public int tid { get; set; }
        public string campaignName { get; set; }
        public int serviceType { get; set; }
        public System.DateTime dateSub { get; set; }
        public Nullable<int> daySub { get; set; }
        public Nullable<int> monthSub { get; set; }
        public Nullable<int> yearSub { get; set; }
        public Nullable<float> unitCost { get; set; }
        public Nullable<float> clicks { get; set; }
        public Nullable<float> leads { get; set; }
        public float OS_clicks { get; set; }
        public System.DateTime dateImported { get; set; }
        public Nullable<float> dup_clicks { get; set; }
    }
}
