//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_stateDesc
    {
        public int sid { get; set; }
        public string state { get; set; }
        public string longState { get; set; }
        public string title { get; set; }
        public string keywords { get; set; }
        public string meta { get; set; }
        public string desc { get; set; }
        public int isLive { get; set; }
    }
}
