//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cpcContent
    {
        public int tid { get; set; }
        public int serviceID { get; set; }
        public string serviceHandle { get; set; }
        public int companyID { get; set; }
        public string companyName { get; set; }
        public string displayName { get; set; }
        public string title { get; set; }
        public string href { get; set; }
        public string altHref { get; set; }
        public string image { get; set; }
        public string alt { get; set; }
        public string h1 { get; set; }
        public bool newWindow { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
