//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FacebookLandingPage
    {
        public int tid { get; set; }
        public Nullable<System.Guid> usersessionid { get; set; }
        public string remoteHost { get; set; }
        public string httpReferer { get; set; }
        public string loginstatus { get; set; }
        public Nullable<bool> clickflag { get; set; }
        public Nullable<bool> permissionflag { get; set; }
        public string uid { get; set; }
        public string username { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string locale { get; set; }
        public string profileUrl { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> birthdayDate { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string zip { get; set; }
        public string timezone { get; set; }
        public Nullable<System.DateTime> lastmodifiedDate { get; set; }
        public Nullable<System.DateTime> stampDate { get; set; }
    }
}
