//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_recordPostInformation
    {
        public int reqID { get; set; }
        public string postData { get; set; }
        public string getData { get; set; }
        public string remoteHost { get; set; }
        public string se { get; set; }
        public string leadType { get; set; }
        public string returnResponse { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string quoteID { get; set; }
        public string referenceID { get; set; }
        public System.DateTime lastModified { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
