//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_movingsurvey
    {
        public int id { get; set; }
        public int quoteid { get; set; }
        public string email { get; set; }
        public string IP { get; set; }
        public string Ans_toQ1 { get; set; }
        public string Ans_toQ2 { get; set; }
        public string Ans_toQ3 { get; set; }
        public string Ans_toQ4 { get; set; }
        public string Ans_toQ5 { get; set; }
        public System.DateTime dateAns { get; set; }
    }
}
