//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bkUpgradeDowngradeCancellation
    {
        public int tid { get; set; }
        public int companyID { get; set; }
        public Nullable<int> serviceID { get; set; }
        public string areaCode { get; set; }
        public string table { get; set; }
        public string Action { get; set; }
        public string who { get; set; }
        public Nullable<System.DateTime> dateLog { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
