//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_monthlyAreaCodeLeadCount
    {
        public int tid { get; set; }
        public string state { get; set; }
        public string areaCode { get; set; }
        public int serviceID { get; set; }
        public Nullable<int> leadCount { get; set; }
        public Nullable<int> numOfCompanies { get; set; }
        public Nullable<decimal> monthlyFee { get; set; }
        public int numCompaniesLeadSent { get; set; }
        public int month { get; set; }
        public int year { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
