//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_URLshortenAPI
    {
        public int tid { get; set; }
        public int verID { get; set; }
        public int emailRowID { get; set; }
        public string longURL { get; set; }
        public string shortURL { get; set; }
        public System.DateTime responseTime { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
