//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_companyAreacode_auto_opt
    {
        public int tid { get; set; }
        public int companyID { get; set; }
        public short areaCode { get; set; }
        public Nullable<short> position { get; set; }
        public string status { get; set; }
        public System.DateTime dateLastBatch { get; set; }
        public int numLeads { get; set; }
    }
}
