//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_affiliateQuotePricingByAreaCode
    {
        public int tid { get; set; }
        public int quoteID { get; set; }
        public string email { get; set; }
        public Nullable<int> serviceID { get; set; }
        public Nullable<int> areaCode { get; set; }
        public string categoryName { get; set; }
        public string serviceName { get; set; }
        public Nullable<int> affiliateID { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> dateSubmitted { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
