//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reverseVerificationCheck
    {
        public int tid { get; set; }
        public Nullable<int> affiliateID { get; set; }
        public string se { get; set; }
        public int verifyFirstName { get; set; }
        public int verifyLastName { get; set; }
        public int verifyEmail { get; set; }
        public int verifyPhone { get; set; }
        public int isAllLeads { get; set; }
        public int isDailyLeadLimit { get; set; }
        public int dailyLeadLimit { get; set; }
        public int dailyLeadCount { get; set; }
        public int frequency { get; set; }
        public int counter { get; set; }
        public int isActive { get; set; }
        public System.DateTime lastLeadDate { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
