//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_phoneOLD
    {
        public int tid { get; set; }
        public string areaCode { get; set; }
        public string prefix { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lng { get; set; }
        public string zip1 { get; set; }
        public string zip2 { get; set; }
        public string zip3 { get; set; }
        public string FIPS { get; set; }
        public string new_areaCode { get; set; }
        public string country { get; set; }
        public string MSA { get; set; }
        public string PMSA { get; set; }
        public string LATA { get; set; }
        public string cell { get; set; }
        public string overlay { get; set; }
    }
}
