//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_agentsAdvertise
    {
        public int tid { get; set; }
        public int agentID { get; set; }
        public string state { get; set; }
        public string county { get; set; }
        public string city { get; set; }
    }
}
