//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_affiliateNotifyAfterLeadSold
    {
        public int rID { get; set; }
        public Nullable<int> postRequestID { get; set; }
        public Nullable<int> quoteID { get; set; }
        public Nullable<int> soldCount { get; set; }
        public Nullable<decimal> price { get; set; }
        public bool isSent { get; set; }
        public Nullable<System.DateTime> sentAt { get; set; }
        public string postURL { get; set; }
        public string postData { get; set; }
        public string postResponse { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
