//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tips
    {
        public int tipid { get; set; }
        public string subject { get; set; }
        public string title { get; set; }
        public string metadescription { get; set; }
        public string metakeywords { get; set; }
        public string h1 { get; set; }
        public string content { get; set; }
        public bool ispublished { get; set; }
        public bool isdeleted { get; set; }
        public System.DateTime lastmodifydate { get; set; }
        public System.DateTime stampdate { get; set; }
    }
}
