//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_companyLeadLimit
    {
        public int tid { get; set; }
        public int companyID { get; set; }
        public Nullable<int> serviceID { get; set; }
        public string areaCode { get; set; }
        public Nullable<int> moveWeightID { get; set; }
        public int isTotalLeadLimit { get; set; }
        public int isDailyLeadLimit { get; set; }
        public int isMonthlyLeadLimit { get; set; }
        public int totalLeadLimit { get; set; }
        public int dailyLeadLimit { get; set; }
        public int monthlyLeadLimit { get; set; }
        public int totalLeadCount { get; set; }
        public int dailyLeadCount { get; set; }
        public int monthlyLeadCount { get; set; }
        public int leadCounter { get; set; }
        public int leadFrequency { get; set; }
        public decimal price { get; set; }
        public System.DateTime lastModified { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
