//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bhTrack
    {
        public int tid { get; set; }
        public string cookiesSupported { get; set; }
        public string cookiesEnabled { get; set; }
        public string browser { get; set; }
        public string browserVer { get; set; }
        public string platform { get; set; }
        public string netFramWorkInstalled { get; set; }
        public string netFramWorkVer { get; set; }
        public string activeXSupported { get; set; }
        public string crawler { get; set; }
        public string emailCrawler { get; set; }
        public string geckoBased { get; set; }
        public string ipAddress { get; set; }
        public string reverseDNS { get; set; }
        public string vbScriptSupported { get; set; }
        public string javascriptSupported { get; set; }
        public string dhtml { get; set; }
        public System.DateTime dateEntered { get; set; }
    }
}
