//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_affiliate_coBrand
    {
        public int cID { get; set; }
        public int affiliateID { get; set; }
        public string header { get; set; }
        public string left_nav { get; set; }
        public string right_nav { get; set; }
        public string footer { get; set; }
        public string color1 { get; set; }
        public string color2 { get; set; }
        public byte showResults { get; set; }
        public byte showMortgage { get; set; }
        public Nullable<int> chosenServiceID { get; set; }
        public string CompanyColor { get; set; }
        public string url_prefix { get; set; }
    }
}
