//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_quoteMoving
    {
        public int quoteID { get; set; }
        public Nullable<int> customerID { get; set; }
        public string cityFrom { get; set; }
        public string cityTo { get; set; }
        public string comments { get; set; }
        public string contactPref { get; set; }
        public string currentZip { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string hPhone { get; set; }
        public string lastName { get; set; }
        public string moveDate { get; set; }
        public string moveWeight { get; set; }
        public Nullable<int> serviceID { get; set; }
        public string stateFrom { get; set; }
        public string stateTo { get; set; }
        public string title { get; set; }
        public string userCookie { get; set; }
        public string wPhone { get; set; }
        public Nullable<System.DateTime> dateSubmitted { get; set; }
    }
}
