//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ballot
    {
        public int ballotID { get; set; }
        public int pollID { get; set; }
        public int voteID { get; set; }
        public int result { get; set; }
        public System.DateTime stampDate { get; set; }
    
        public virtual tbl_poll tbl_poll { get; set; }
        public virtual tbl_vote tbl_vote { get; set; }
    }
}
