//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_listLinks
    {
        public int linkID { get; set; }
        public int listID { get; set; }
        public string keyWords { get; set; }
        public string zipcode { get; set; }
        public int serviceID { get; set; }
        public string link { get; set; }
        public System.DateTime dateSubmitted { get; set; }
    
        public virtual tbl_listMain tbl_listMain { get; set; }
    }
}
