//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invalidQuotes
    {
        public int postID { get; set; }
        public string cityFrom { get; set; }
        public string cityTo { get; set; }
        public string contactPref { get; set; }
        public string currentZip { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string hPhone { get; set; }
        public string lastName { get; set; }
        public string moveDate { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string yearVehic { get; set; }
        public string runCond { get; set; }
        public string moveWeight { get; set; }
        public Nullable<int> serviceID { get; set; }
        public string stateFrom { get; set; }
        public string stateTo { get; set; }
        public string wPhone { get; set; }
        public string httpReferer { get; set; }
        public string remoteHost { get; set; }
        public string keyword { get; set; }
        public string Se { get; set; }
        public Nullable<int> postRequestID { get; set; }
        public System.DateTime dateSubmitted { get; set; }
    }
}
