//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_p4pOffers
    {
        public int offerID { get; set; }
        public int postID { get; set; }
        public long exchangeID { get; set; }
        public string providerMoverID { get; set; }
        public string moversName { get; set; }
        public decimal offeredPrice { get; set; }
        public bool isOfferAccepted { get; set; }
        public System.DateTime timeStamp { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
