//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_affiliatePricingByAreaCode
    {
        public int tid { get; set; }
        public int affiliateID { get; set; }
        public int areaCode { get; set; }
        public decimal longSmall { get; set; }
        public decimal longMedium { get; set; }
        public decimal longLarge { get; set; }
        public decimal longUnknown { get; set; }
        public decimal localSmall { get; set; }
        public decimal localMedium { get; set; }
        public decimal localLarge { get; set; }
        public decimal localUnknown { get; set; }
        public decimal intlSmall { get; set; }
        public decimal intlMedium { get; set; }
        public decimal intlLarge { get; set; }
        public decimal intlUnknown { get; set; }
    }
}
