//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emailDetailsFromRealTimeAPI
    {
        public int tid { get; set; }
        public string email { get; set; }
        public Nullable<int> postRequestID { get; set; }
        public string Box { get; set; }
        public string Domain { get; set; }
        public Nullable<int> IsRecognizedTLD { get; set; }
        public string TopLevelDomain { get; set; }
        public string TopLevelDomainDescription { get; set; }
        public Nullable<int> IsCCTLD { get; set; }
        public Nullable<int> IsSyntaxGood { get; set; }
        public Nullable<int> IsDomainSpecificSyntaxGood { get; set; }
        public Nullable<int> IsDNSGood { get; set; }
        public string IsSMTPServerGood { get; set; }
        public string IsCatchAllDomain { get; set; }
        public string IsSMTPMailBoxGood { get; set; }
        public string IsFree { get; set; }
        public Nullable<int> IsEstablished { get; set; }
        public Nullable<int> IsAlias { get; set; }
        public string PossibleFirstName { get; set; }
        public string PossibleLastName { get; set; }
        public Nullable<int> IsSMSDomain { get; set; }
        public Nullable<int> IsRole { get; set; }
        public string IsDeliverable { get; set; }
        public string IsBusinessAddress { get; set; }
        public Nullable<int> isGood { get; set; }
        public Nullable<int> isBogus { get; set; }
        public Nullable<int> isVulgar { get; set; }
        public System.DateTime lastModified { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
