//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reviews
    {
        public int reviewID { get; set; }
        public Nullable<long> companyID { get; set; }
        public string companyName { get; set; }
        public string companyNameUser { get; set; }
        public string handle { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string subject { get; set; }
        public string description { get; set; }
        public Nullable<byte> isPub { get; set; }
        public System.DateTime displayDate { get; set; }
        public System.DateTime stampDate { get; set; }
        public byte isActive { get; set; }
        public string IP { get; set; }
        public bool isFree { get; set; }
        public bool isComplaintFiled { get; set; }
        public string quoteID { get; set; }
        public string cityFrom { get; set; }
        public string stateFrom { get; set; }
        public string cityTo { get; set; }
        public string stateTo { get; set; }
        public Nullable<int> estimatedPrice { get; set; }
        public Nullable<int> finalCost { get; set; }
    }
}
