//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vote
    {
        public tbl_vote()
        {
            this.tbl_ballot = new HashSet<tbl_ballot>();
        }
    
        public int voteID { get; set; }
        public string description { get; set; }
        public System.DateTime stampDate { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<tbl_ballot> tbl_ballot { get; set; }
    }
}
