//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_realtimeReversePhoneLookup
    {
        public int tid { get; set; }
        public string phoneNumberIn { get; set; }
        public string phoneNumberClean { get; set; }
        public string providerName { get; set; }
        public string providerCity { get; set; }
        public string providerState { get; set; }
        public string providerLineType { get; set; }
        public string providerLatitude { get; set; }
        public string providerLongitude { get; set; }
        public string contactName { get; set; }
        public string contactAddress { get; set; }
        public string contactCity { get; set; }
        public string contactState { get; set; }
        public string contactZip { get; set; }
        public string contactType { get; set; }
        public string contactQuality { get; set; }
        public string tokensUsed { get; set; }
        public string isConnected { get; set; }
        public string recommendConnectionCheck { get; set; }
        public string debug { get; set; }
        public string errorType { get; set; }
        public string errorTypeCode { get; set; }
        public string errorDesc { get; set; }
        public string errorDescCode { get; set; }
        public Nullable<int> postRequestID { get; set; }
        public System.DateTime lastModified { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
