//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_complaints
    {
        public int complaintID { get; set; }
        public long companyID { get; set; }
        public string subject { get; set; }
        public string comments { get; set; }
        public System.DateTime dateSubmitted { get; set; }
        public System.DateTime dateAdded { get; set; }
        public int reviewID { get; set; }
    }
}
