//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_p4pPostLog
    {
        public int postID { get; set; }
        public int areaCode { get; set; }
        public Nullable<int> quoteID { get; set; }
        public Nullable<decimal> price { get; set; }
        public string message { get; set; }
        public int code { get; set; }
        public Nullable<bool> isOfferAccepted { get; set; }
        public byte step { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
