//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_listMain
    {
        public tbl_listMain()
        {
            this.tbl_listLinks = new HashSet<tbl_listLinks>();
        }
    
        public int listID { get; set; }
        public string listName { get; set; }
        public System.DateTime dateSubmitted { get; set; }
    
        public virtual ICollection<tbl_listLinks> tbl_listLinks { get; set; }
    }
}
