//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_companyRefundLeads
    {
        public int leadID { get; set; }
        public Nullable<int> creditID { get; set; }
        public int quoteID { get; set; }
        public int companyID { get; set; }
        public int companyQuoteTrackID { get; set; }
        public decimal creditPrice { get; set; }
        public string refundRequest { get; set; }
        public string notes { get; set; }
        public string creditApprovedBy { get; set; }
        public Nullable<System.DateTime> approveDate { get; set; }
        public Nullable<System.DateTime> creditAppliedDate { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
