//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_company_metatags
    {
        public long companyID { get; set; }
        public string title { get; set; }
        public string metaKeywords { get; set; }
        public string metaDescription { get; set; }
    }
}
