//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_company_flagLeads
    {
        public int tid { get; set; }
        public int companyID { get; set; }
        public int quoteID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string hPhone { get; set; }
        public string cEmail { get; set; }
        public bool Phone { get; set; }
        public bool Email { get; set; }
        public bool Name { get; set; }
        public bool Duplicate { get; set; }
        public bool truckRental { get; set; }
        public bool Other { get; set; }
        public string se { get; set; }
        public string leadType { get; set; }
        public System.DateTime leadDate { get; set; }
        public System.DateTime stampDate { get; set; }
        public string keyword { get; set; }
        public string remoteHost { get; set; }
    }
}
