//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pageMain
    {
        public int pageID { get; set; }
        public Nullable<int> serviceID { get; set; }
        public string GeoLocation { get; set; }
        public int listID { get; set; }
        public string pageName { get; set; }
        public System.DateTime dateSubmitted { get; set; }
    }
}
