//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_articlesForHomePage
    {
        public int tid { get; set; }
        public int articleID { get; set; }
        public string title { get; set; }
        public string href { get; set; }
        public int category { get; set; }
        public System.DateTime datesubmitted { get; set; }
    }
}
