//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_affiliateMain
    {
        public int affiliateID { get; set; }
        public string affiliateName { get; set; }
        public string affiliateHandle { get; set; }
        public string comments { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<int> islink { get; set; }
        public Nullable<int> showClicksReport { get; set; }
        public Nullable<int> isCobrand { get; set; }
        public bool areaCodePriced { get; set; }
        public bool trackAds { get; set; }
        public bool isRealTimeResponse { get; set; }
        public string vendorID { get; set; }
        public string affiliateType { get; set; }
        public bool isActive { get; set; }
        public bool isPaidFlaggedLeads { get; set; }
        public System.DateTime dateCreated { get; set; }
    }
}
