//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_zipNew_Front
    {
        public Nullable<int> tid { get; set; }
        public string zip { get; set; }
        public string state { get; set; }
        public string longState { get; set; }
        public string cityName { get; set; }
        public string countyName { get; set; }
        public string timeZone { get; set; }
        public string pref { get; set; }
        public string TYP { get; set; }
        public string FIPS { get; set; }
        public Nullable<double> LAT { get; set; }
        public Nullable<double> LNG { get; set; }
        public string areaCode { get; set; }
        public string FINANCE { get; set; }
        public string LL { get; set; }
        public string FAC { get; set; }
        public string MSA { get; set; }
        public string PMSA { get; set; }
        public string FILLER { get; set; }
    }
}
