//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_affiliate
    {
        public int affiliateID { get; set; }
        public string link { get; set; }
        public byte landing_page { get; set; }
        public Nullable<byte> isCobrand { get; set; }
        public string url_prefix { get; set; }
        public string se_id { get; set; }
        public System.DateTime dateCreated { get; set; }
    }
}
