//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_companyManualEmailsLog
    {
        public int tid { get; set; }
        public int companyID { get; set; }
        public int quoteID { get; set; }
        public string companyEmail { get; set; }
        public string mailBcc { get; set; }
        public bool infoByArea { get; set; }
        public string who { get; set; }
        public System.DateTime dateLog { get; set; }
    }
}
