//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reverseVerificationMaskPhone
    {
        public int tid { get; set; }
        public Nullable<int> verID { get; set; }
        public Nullable<int> postRequestID { get; set; }
        public Nullable<int> quoteID { get; set; }
        public string leadType { get; set; }
        public string originalPhone { get; set; }
        public string maskPhone { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
