//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_collectionList
    {
        public int tid { get; set; }
        public int companyID { get; set; }
        public decimal amountOwed { get; set; }
        public System.DateTime dateAddedInCollection { get; set; }
        public string reason { get; set; }
        public string contactPerson { get; set; }
        public System.DateTime dateSubmitted { get; set; }
    }
}
