//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reverseVerificationLeadsCall
    {
        public int tid { get; set; }
        public Nullable<int> verID { get; set; }
        public string twilioID { get; set; }
        public string processFrom { get; set; }
        public string callFlow { get; set; }
        public Nullable<int> verificationResponse { get; set; }
        public string FailedResponse { get; set; }
        public System.DateTime lastModified { get; set; }
        public Nullable<System.DateTime> callEnds { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
