//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_campaignInfo
    {
        public int campaignID { get; set; }
        public string campaignName { get; set; }
        public string description { get; set; }
        public string link { get; set; }
        public Nullable<int> serviceType { get; set; }
        public Nullable<float> unitCost { get; set; }
        public string type { get; set; }
        public System.DateTime dateStarted { get; set; }
        public byte isActive { get; set; }
    }
}
