//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_quoteAnalysis
    {
        public int tid { get; set; }
        public long quoteID { get; set; }
        public int areaCode { get; set; }
        public int serviceID { get; set; }
        public string categoryName { get; set; }
        public string remoteHost { get; set; }
        public string httpReferer { get; set; }
        public string keyword { get; set; }
        public string query { get; set; }
        public string se { get; set; }
        public string source { get; set; }
        public string type { get; set; }
        public Nullable<int> affiliateID { get; set; }
        public decimal cost { get; set; }
        public System.DateTime dateSubmitted { get; set; }
        public Nullable<System.DateTime> stampDate { get; set; }
    }
}
