//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_realEstateAgents
    {
        public int agentID { get; set; }
        public string agentSource { get; set; }
        public Nullable<int> agentSourceID { get; set; }
        public string agentName { get; set; }
        public string agentCompanyName { get; set; }
        public string agentAddress { get; set; }
        public string agentAddress2 { get; set; }
        public string agentCity { get; set; }
        public string agentCounty { get; set; }
        public string agentState { get; set; }
        public string agentZip { get; set; }
        public string agentZip4 { get; set; }
        public string agentPhone1 { get; set; }
        public string agentPhone2 { get; set; }
        public string agentFax { get; set; }
        public string agentWebsite { get; set; }
        public string agentEmail { get; set; }
        public string agentTitle { get; set; }
        public string agentDesc { get; set; }
        public string agentImage { get; set; }
        public bool isActive { get; set; }
        public System.DateTime insertDate { get; set; }
        public byte isFeatured { get; set; }
    }
}
