//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_companyAreacode
    {
        public int tid { get; set; }
        public int companyID { get; set; }
        public int serviceID { get; set; }
        public short areaCode { get; set; }
        public Nullable<short> position { get; set; }
        public string status { get; set; }
        public System.DateTime dateLastBatch { get; set; }
        public int numLeads { get; set; }
        public int isForceSelect { get; set; }
        public int isOriginZipCode { get; set; }
        public int isDestinationZipCode { get; set; }
        public int isDestinationAreaCode { get; set; }
        public int isMoveWeightSelect { get; set; }
        public int isMoveDistanceSelect { get; set; }
        public int isSpecificOriginDestinationState { get; set; }
        public int isSpecificOriginDestinationAreacode { get; set; }
    
        public virtual tbl_companyPhoneAreaMapping tbl_companyPhoneAreaMapping { get; set; }
    }
}
