//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dailyAffilaiteBudget
    {
        public int tid { get; set; }
        public string vendorID { get; set; }
        public string affiliateName { get; set; }
        public Nullable<decimal> notificationTotal { get; set; }
        public Nullable<decimal> maxTotal { get; set; }
        public int isNotification { get; set; }
        public Nullable<System.DateTime> lastNotificationAt { get; set; }
        public int isBlocked { get; set; }
        public string blockedIDs { get; set; }
        public System.DateTime blockedAt { get; set; }
        public System.DateTime stampdate { get; set; }
    }
}
