//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emailValidationDetails
    {
        public int tid { get; set; }
        public Nullable<int> postRequestID { get; set; }
        public Nullable<int> score { get; set; }
        public string isDeliverable { get; set; }
        public string emalAddressIn { get; set; }
        public string emailAddressOut { get; set; }
        public Nullable<bool> emailCorrected { get; set; }
        public string box { get; set; }
        public string domain { get; set; }
        public string topLevelDomain { get; set; }
        public string topLevelDomainDescription { get; set; }
        public string isSMTPServerGood { get; set; }
        public string isCatchAllDomain { get; set; }
        public string isSMTPMailBoxGood { get; set; }
        public string warningCodes { get; set; }
        public string warningDescriptions { get; set; }
        public string notesCodes { get; set; }
        public string notesDescription { get; set; }
        public string errorType { get; set; }
        public string errorTypeCode { get; set; }
        public string errorDesc { get; set; }
        public string errorDescCode { get; set; }
        public System.DateTime lastModified { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
