//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_auto_opt_companyMain
    {
        public int companyID { get; set; }
        public bool isActive { get; set; }
        public bool isDailyLimit { get; set; }
        public bool isMontlyLimit { get; set; }
        public int MaxDailyLeads { get; set; }
        public int MaxMontlyLeads { get; set; }
        public int DailyLeadsCount { get; set; }
        public int MonthlyLeadsCount { get; set; }
        public System.DateTime LastLeadDate { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
