//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_callsource
    {
        public string callID { get; set; }
        public string campaignID { get; set; }
        public string callerNumber { get; set; }
        public string trackNumber { get; set; }
        public string targetNumber { get; set; }
        public Nullable<System.DateTime> callTime { get; set; }
        public string duration { get; set; }
        public string callResult { get; set; }
        public string VoiceID { get; set; }
        public string voiceFileName { get; set; }
        public string callerZIPcode { get; set; }
        public string callerLong { get; set; }
        public string callerLat { get; set; }
        public string addressErrorLevel { get; set; }
        public string firstName { get; set; }
        public string Initial { get; set; }
        public string lastName { get; set; }
        public string streetNumber { get; set; }
        public string streetDirection { get; set; }
        public string streetName { get; set; }
        public string aptNumber { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string ZIP4 { get; set; }
        public string customerName { get; set; }
        public string callType { get; set; }
        public string timeZone { get; set; }
        public string campaignName { get; set; }
        public string adSource { get; set; }
        public int tid { get; set; }
        public System.DateTime dateInsert { get; set; }
        public string offset { get; set; }
    }
}
