//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_companyBudget
    {
        public int tid { get; set; }
        public int companyID { get; set; }
        public Nullable<int> serviceID { get; set; }
        public string areaCode { get; set; }
        public Nullable<int> moveWeightID { get; set; }
        public decimal totalBudget { get; set; }
        public decimal remainingBudget { get; set; }
        public Nullable<int> lastQuoteID { get; set; }
        public Nullable<decimal> lastQuotePrice { get; set; }
        public System.DateTime lastModified { get; set; }
        public System.DateTime stampDate { get; set; }
        public string budgetAction { get; set; }
        public string budgetNote { get; set; }
        public bool isRecurring { get; set; }
        public bool isRequireNoticeToCharge { get; set; }
        public bool isOneTimeRenew { get; set; }
        public int minDaysToCharge { get; set; }
        public string agreementNumber { get; set; }
    }
}
