//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_companyRefundReasons
    {
        public int ID { get; set; }
        public string reason { get; set; }
        public string reasonDescription { get; set; }
        public bool isActive { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
