//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_resultPageContent
    {
        public int tid { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public int serviceID { get; set; }
        public string title { get; set; }
        public string metaKeywords { get; set; }
        public string metaDescription { get; set; }
        public string H1 { get; set; }
        public string subH1 { get; set; }
        public string bcService { get; set; }
        public string bcState { get; set; }
        public string bcCity { get; set; }
        public string content { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
