//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_farmerBannerResponse
    {
        public int rID { get; set; }
        public Nullable<int> quoteID { get; set; }
        public string remoteHost { get; set; }
        public string httpReferer { get; set; }
        public string userAgent { get; set; }
        public string pageUrl { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
