//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Auto
    {
        public int tid { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<decimal> price { get; set; }
        public string formatDate { get; set; }
        public System.DateTime dateInsert { get; set; }
    }
}
