//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_zip
    {
        public string cityName { get; set; }
        public string state { get; set; }
        public string zipCode { get; set; }
        public string areaCode { get; set; }
        public string FIPS { get; set; }
        public string countyName { get; set; }
        public string pref { get; set; }
        public string timeZone { get; set; }
        public string DST { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> @long { get; set; }
        public string MSA { get; set; }
        public string PMSA { get; set; }
        public string cDist { get; set; }
        public string DMA { get; set; }
        public string type { get; set; }
        public string longState { get; set; }
        public int tid { get; set; }
    }
}
