//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_paidComp_inactive
    {
        public int companyID { get; set; }
        public string compName { get; set; }
        public string companyHandle { get; set; }
        public string companyName2 { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string zip_4 { get; set; }
        public string linkEx { get; set; }
        public string longstate { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> serviceid { get; set; }
        public int tid { get; set; }
    }
}
