//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_affiliate_CobrandNew
    {
        public int tid { get; set; }
        public int affiliateID { get; set; }
        public string pageHtml { get; set; }
        public string formStyles { get; set; }
        public string buttonImagePath { get; set; }
        public string imageAlt { get; set; }
        public string thankYouMessage { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
