//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_upgradeDowngradesCancelStatusLog
    {
        public int tid { get; set; }
        public string process { get; set; }
        public Nullable<int> errorNumber { get; set; }
        public Nullable<int> errorLine { get; set; }
        public string errorProcedure { get; set; }
        public string errorMessage { get; set; }
        public bool isSucceeded { get; set; }
        public System.DateTime stampDate { get; set; }
    }
}
