//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tl_companyPricePerLead
    {
        public int tid { get; set; }
        public int companyID { get; set; }
        public Nullable<int> serviceID { get; set; }
        public string areaCode { get; set; }
        public Nullable<int> moveWeightID { get; set; }
        public decimal price { get; set; }
        public string action { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> stampDate { get; set; }
        public Nullable<System.DateTime> loggedDate { get; set; }
    }
}
