//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tl_company_advertisement_log
    {
        public int tid { get; set; }
        public int companyID { get; set; }
        public int serviceID { get; set; }
        public string adminAction { get; set; }
        public string states { get; set; }
        public System.DateTime dateLog { get; set; }
        public string emailLogged { get; set; }
    }
}
