//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tl_postInformation
    {
        public int reqID { get; set; }
        public Nullable<int> postRequestID { get; set; }
        public string postData { get; set; }
        public string getData { get; set; }
        public string remoteHost { get; set; }
        public string se { get; set; }
        public string leadType { get; set; }
        public string returnResponse { get; set; }
        public string quoteID { get; set; }
        public string landingPage { get; set; }
        public string referenceID { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public Nullable<System.DateTime> stampDate { get; set; }
        public System.DateTime logDate { get; set; }
    }
}
