//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123Movers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tl_quoteRequests
    {
        public int tid { get; set; }
        public int requestID { get; set; }
        public string zipFrom { get; set; }
        public string zipTo { get; set; }
        public string cityTo { get; set; }
        public string stateTo { get; set; }
        public string moveDate { get; set; }
        public string moveWeight { get; set; }
        public string vehiclemake { get; set; }
        public string vehiclemodel { get; set; }
        public string vehicleyear { get; set; }
        public string vehicleRunningCondition { get; set; }
        public string se { get; set; }
        public string keyword { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> serviceID { get; set; }
        public string servingCompanies { get; set; }
        public Nullable<int> postRequestID { get; set; }
        public string httpreferer { get; set; }
        public string remoteHost { get; set; }
        public string userAgent { get; set; }
        public Nullable<System.DateTime> servingCompaniesFountAt { get; set; }
        public string consent { get; set; }
        public Nullable<System.DateTime> checkAt { get; set; }
        public Nullable<System.DateTime> postRequestAt { get; set; }
        public Nullable<System.DateTime> stampDate { get; set; }
        public System.DateTime logDate { get; set; }
    }
}
